### PR TITLE
Add parameters for file/directory modes

### PR DESCRIPTION
**Pull request by ludovicus3**
Some security scans don't like the default file modes set by this module. I have added parameters to allow for the adjustment of the file modes for this ability to resolve this issue per the users desires.

### CODE REVIEW

**Comment by TheMeier** [comment]
Please update `REFERENCE.md` see https://voxpupuli.org/docs/how_to_run_tests/#referencemd-update

**Comment by ludovicus3** [comment]
I don't have any major argument against that other than parameters that refer to the crontab and such are prefixed crontab_ but I could change it if it's preferred.

**Comment by TheMeier** [comment]
Well what triggerd this comment is that the crontab-prefixed parameters seem to go inside the templated content opposed to any other parameters

**Comment by TheMeier** [comment]
Ok an excception is `crontab_run_parts` which is used in the puppet DSL and in the epp

**Review by TheMeier — APPROVED** [review]

**Pull request merged**
